### PR TITLE
fix: Wayland region capture under fractional scaling

### LINKED ISSUE #9: Wayland region capture: black area / wrong output size
On Wayland, region capture produces an image with a large black area and an incorrect output size
The grim binary does not show this issue on the same setup, so this looks like a coordinate/scale mismatch during capture/compositing.
I’m opening a fork to work on a fix and will submit a PR to this repo once validated. I can attach a photo showing the bug if needed.

Here is the grim output with a size of 1920x1200 :
Image

And here is the grim-rs output with a size of 1280x800 : 
Image

### PR DESCRIPTION
**Pull request by Jeremis70**
Fixes #9.

On compositors with fractional scaling enabled, region captures could produce incorrect dimensions and/or large black areas due to logical vs physical coordinate mismatches.

What changed

When fractional logical scaling is present, avoid protocol-level “region capture” paths that assume integer scaling.
Capture full outputs and then composite + software crop/resize to produce a correctly-mapped region image.
API

Expose [Grim::greatest_scale_for_region(region)](vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) to match grim’s “default scale selection” logic (greatest logical scale among outputs intersecting the region).
How to match grim’s default scale (optional)
If you want the most “grim-like” scale for a region capture, pick the scale first and then call the explicit *_with_scale APIs:
use grim_rs::{Box, Grim};
``` rust
fn main() -> grim_rs::Result<()> {
    let mut grim = Grim::new()?;

    let region = Box::new(0, 0, 1280, 800);

    // Pick a default scale like grim (greatest logical output scale intersecting the region)
    let scale = grim.greatest_scale_for_region(Some(region))?;

    let result = grim.capture_region_with_scale(region, scale)?;
    grim.save_png(result.data(), result.width(), result.height(), "region.png")?;

    Ok(())
}
```

Screenshots

grim-rs (before): 
Image
grim-rs (after): 
image
grim (reference): 
Image

---

<a href="https://app.devin.ai/review/shikoucore/grim-rs/pull/10">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: src/wayland_capture.rs [hunk 1]
```diff
@@ -639,6 +909,174 @@ impl WaylandCapture {
...
+        }
+
+        Ok(CaptureResult {
+            data: dest,
+            width: dest_width as u32,
+            height: dest_height as u32,
+        })
+    }
+
+    fn resize_image_data_to(
```
Comment (vremyavnikuda) [inline src/wayland_capture.rs]: i haven't figured out yet how to use it other than this fix, if only as a replacement for **scale_image_data**, but in that case, why do we need the coefficient

File: src/wayland_capture.rs [hunk 2]
```diff
@@ -253,6 +273,46 @@ fn blit_capture(
     }
 }
 
+fn crop_rgba(
```
Comment (vremyavnikuda) [inline src/wayland_capture.rs]: del
we use direct capture of the region in **capture_region_for_output** directly from the composite

File: src/wayland_capture.rs [hunk 3]
```diff
@@ -1125,6 +1535,117 @@ impl WaylandCapture {
     }
 }
 
+fn greatest_logical_scale_for_region_from_entries<I>(
```
Comment (vremyavnikuda) [inline src/wayland_capture.rs]: [view](https://github.com/shikoucore/grim-rs/pull/10/files#r2702685445)

File: src/wayland_capture.rs [hunk 4]
```diff
@@ -1125,6 +1535,117 @@ impl WaylandCapture {
...
+        return Err(Error::InvalidRegion(
+            "Capture region does not intersect with any output".to_string(),
+        ));
+    }
+
+    Ok(max_scale)
+}
+
+#[cfg(test)]
+mod tests {
```
Comment (vremyavnikuda) [inline src/wayland_capture.rs]: there should be no tests in wayland_capture 
if possible, transfer them to ../test/

File: CHANGELOG.md [hunk 5]
```diff
@@ -5,6 +5,11 @@ All notable changes to this project will be documented in this file.
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
+## [Unreleased]
```
Comment (vremyavnikuda) [inline CHANGELOG.md]: release 0.1.4
